13 read accepted payments
SAMAHAN-Systems-Development/ACMS-backend-2023 pull request #19
Opened 2023-12-27 06:15 UTC by SaaammmyyyS

Users can now access accepted payments with a limit of 10 data entries per page

2023-12-27 12:40 UTC, rhaeyx commented on .env
ibalik to 54322, tapos itry with supabase

2023-12-29 04:35 UTC, rhaeyx requested changes

2023-12-29 04:35 UTC, rhaeyx commented on src/app.module.ts
pa confirm ko ya @viverbungag , pero pwede na ata dili i-apil ang PaymentController ug PaymentService diri since part na siya sa PaymentModule. Isa pud ata ni sa reason mag error ang jest, kanang mag doble ang pag import.

2023-12-29 04:35 UTC, rhaeyx commented on prisma/migrations/20231226095622_/migration.sql
pa rename diay ko ani na migration added_requires_payment

2023-12-29 04:35 UTC, rhaeyx commented on src/payment/payment.service.ts
iparameter nalang pud ang default na ireturn na # of elements, para future proof nalang pud

2023-12-29 04:50 UTC, viverbungag commented on src/app.module.ts
yiss yisss dle na need butangan ang sa controllers ug providers, sa imports lng ang butangan

2023-12-29 14:20 UTC, rhaeyx approved these changes

2023-12-29 14:22 UTC, merged