1 login of facilitator cashier and admin
SAMAHAN-Systems-Development/ACMS-backend-2023 pull request #31
Opened 2024-01-05 13:15 UTC by ErriekaP

2024-01-06 03:55 UTC, rhaeyx requested changes
hello, do you have prettier installed? if you dont, i recommend installing prettier also can you add the .env variables to the .env.example template

2024-01-06 03:55 UTC, rhaeyx commented on src/users/user.controller.ts
> +    private readonly prismaService: UserService,
pwede pa rename to userService yung prismaService

2024-01-06 03:55 UTC, rhaeyx commented on src/users/user.service.ts
> +    });
hello, can i ask for the reason for why ganto structure and 
```
    const prismaData: Prisma.UsersCreateInput = {
      email: data.email,
      userType: data.userType,
      supabaseUserId: user.id
    };


    return this.prismaService.users.create({
      data: prismaData,
    });
```
not like this? if no particular reason, pwede pa change ako into this thank u
```
    return await this.prismaService.users.create({
      data: {
        email: data.email,
        userType: data.userType,
        supabaseUserId: user.id,
      },
    });
```

2024-01-06 03:55 UTC, rhaeyx commented on src/users/user.controller.ts
> +  @Post('register')
for testing purposes lang eto na endpoint? if this is used for creating users for the sake of testing, i think a seeder would be more appropriate

2024-01-06 03:55 UTC, rhaeyx commented on src/users/user.controller.ts
> +import * as bcrypt from 'bcrypt';
unused import

2024-01-06 03:55 UTC, rhaeyx commented on prisma/schema.prisma
> +model Users {
rename Users model to User

https://www.prisma.io/docs/orm/reference/prisma-schema-reference#naming-conventions

2024-01-06 03:55 UTC, rhaeyx commented on prisma/migrations/20231228133822_added_users_model/migration.sql
> +ALTER TABLE "Event" ADD COLUMN     "requires_payment" BOOLEAN NOT NULL DEFAULT true;
pwede pa remove ng lines 1 and 2, cause mag error ang migration cause part eto ng iba na migration

2024-01-06 03:55 UTC, rhaeyx commented on src/app.module.ts
> +import { UsersModule } from './users/user.module';
rename to `UsersModule` to `UserModule` please

2024-01-06 03:55 UTC, rhaeyx commented on src/prisma/prisma.service.ts
> +import {PrismaClient } from '@prisma/client';
add space in between { and PrismaClient

import { PrismaClient } from '@prisma/client';

2024-01-06 03:55 UTC, rhaeyx commented on prisma/schema.prisma
> +
please remove extra line

2024-01-06 03:55 UTC, rhaeyx commented on supabase/supabase.service.ts
> +    const supabaseAPIKey = process.env.SUPABASE_URL;
shouldnt supabaseAPIKey be the supabase anon key? not sure bakit di nag eerror but either way can you set this to the anon key

2024-01-06 04:15 UTC, rhaeyx commented
@ErriekaP nag commit ako ng users seeder, you can run it with `npm run prisma:migrate:reset`. pwede mo to gamitin instead of the register na route.

note: this will reset the db, madelete yung old data

2024-01-06 04:41 UTC, ErriekaP commented on src/users/user.controller.ts
> +  @Post('register')
Hi Francis! Nasali sa seeder ang sa supabase na auth?

2024-01-06 06:57 UTC, rhaeyx commented on src/users/user.controller.ts
> +  @Post('register')
yess, `npm run prisma:migrate:reset` lang to seed though matanggal yung previously registered accounts if mag seed

2024-01-11 09:41 UTC, viverbungag commented
Already added route guards for all the routes except the creation of students

2024-01-12 04:13 UTC, viverbungag commented
Laters nlng nako iactivate ang guards kai basig manlisod ang uban

2024-01-12 13:25 UTC, rhaeyx commented
> Laters nlng nako iactivate ang guards kai basig manlisod ang uban

What if mag add lang ta ug 

```
if (process.env.ENVIRONMENT === "dev") { return true } 
``` 
sa canActivate sa guard ya?

2024-01-12 13:44 UTC, viverbungag commented
okeokeoke pedee

2024-01-12 14:08 UTC, rhaeyx commented
ikaw na merge ani ya @viverbungag ?

2024-01-13 02:16 UTC, viverbungag commented
okeokeoke ako na merge ani

2024-01-13 02:16 UTC, viverbungag commented
reopen nlng nato kung naai problem

2024-01-13 02:16 UTC, merged